# Generated by Django 6.1.1 on 2026-09-24 05:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Maxflow Controls ( I ) Pvt. Ltd.', max_length=255)),
                ('company_address', models.TextField(default='18, Unique Industrial Estate, Off. Veer Savarkar Marg, Prabhadevi, Mumbai – 400 025')),
                ('company_phone', models.CharField(default='022-2436 0131 / 32, 2437 1847', max_length=100)),
                ('company_fax', models.CharField(blank=True, default='022-2430 6945', max_length=100, null=True)),
                ('company_email', models.EmailField(default='mumbai@maxflowcontrols.com', max_length=254)),
                ('company_gstin', models.CharField(blank=True, default='27AABCM8025D1ZQ', max_length=50, null=True)),
                ('quotation_number', models.CharField(max_length=100, unique=True, verbose_name='Quotation / Ref. No.')),
                ('quotation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Quotation Date')),
                ('salutation', models.CharField(default='DEAR SIR,', max_length=100)),
                ('subject', models.TextField(default='WE ARE PLEASED TO QUOTE FOR THE DANFOSS HYDRAULIC ITEM AGAINST YOUR TENDER / INQUIRY AS FOLLOWS:', verbose_name='Subject / Opening Note')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer / Company Name')),
                ('customer_address', models.TextField(verbose_name='Customer Address')),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_gstin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer GSTIN')),
                ('price_terms', models.CharField(default='F.O.R., DESTINATION', max_length=255, verbose_name='Prices Terms')),
                ('discount_terms', models.CharField(default='NET.', max_length=255, verbose_name='Discount Terms')),
                ('tax_terms', models.CharField(default='AS INDICATED ABOVE (GST Extra)', max_length=255, verbose_name='Tax Terms')),
                ('payment_terms', models.CharField(default='100% AGAINST DELIVERY WITHIN 30 DAYS', max_length=255, verbose_name='Payment Terms')),
                ('validity_terms', models.CharField(default='30 DAYS.', max_length=255, verbose_name='Validity')),
                ('special_notes', models.TextField(blank=True, default='IN CASE OF ANY PRICE INCREASE / ADDL. SURCHARGE LEVIED BY OUR PRINCIPALS AT THE TIME OF DELIVERY, SUCH REVISED PRICE ONLY WILL APPLY. ALSO P.O. ONCE PLACED CANNOT BE CANCELLED OR AMENDED UNDER ANY CIRCUMSTANCES AS THE ITEM IS IMPORTED & WE ARE NOT INSISTING FOR ANY ADVANCE PAYMENT AS IN THE CASE OF OTHERS.', null=True, verbose_name='Special / P.N. Notes')),
                ('signatory_company', models.CharField(default='MAXFLOW CONTROLS (I) PVT. LTD.', max_length=255)),
                ('signatory_name', models.CharField(default='DINENDRA CHARI', max_length=100)),
                ('signatory_designation', models.CharField(default='MANAGER TECHNICAL', max_length=100)),
                ('signatory_phone', models.CharField(blank=True, default='8928386419', max_length=50, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(default='1', max_length=20, verbose_name='Sr. #')),
                ('description', models.TextField(verbose_name='Description of Item')),
                ('hsn_code', models.CharField(blank=True, default='', max_length=50, verbose_name='HSN Code')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Qty.')),
                ('unit', models.CharField(blank=True, default='NOS', max_length=30, verbose_name='Unit')),
                ('unit_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Unit Rate (Rs.)')),
                ('delivery_schedule', models.CharField(blank=True, default='EX STOCK', max_length=150, verbose_name='Del. Schedule')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='GST %')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Amount (Rs.)')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
