# Generated by Django 6.1.1 on 2026-09-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(choices=[('PCS', 'PCS'), ('SET', 'SET'), ('NOS', 'NOS'), ('MTR', 'MTR'), ('KG', 'KG'), ('LOT', 'LOT'), ('PKT', 'PKT'), ('PAIR', 'PAIR')], default='NOS', max_length=30, verbose_name='Unit'),
        ),
    ]
