# Generated by Django 6.1.1 on 2026-09-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_alter_quotationitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='company_pan',
            field=models.CharField(blank=True, default='AABCM8025D', max_length=50, null=True, verbose_name='Company PAN'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='company_gstin',
            field=models.CharField(blank=True, default='27AABCM8025D1ZQ', max_length=50, null=True, verbose_name='Company GSTIN'),
        ),
    ]
