# Generated by Django 6.1.1 on 2026-09-24 09:29

import quotations.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_quotation_company_pan_alter_quotation_company_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Discount %'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(default=quotations.models.get_next_quotation_number, max_length=100, unique=True, verbose_name='Quotation / Ref. No.'),
        ),
    ]
