# Generated by Django 6.1.1 on 2026-09-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_quotation_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='GST %'),
        ),
    ]
