# Generated by Django 6.1.1 on 2026-09-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_alter_quotationitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='freight_terms',
            field=models.CharField(default='EXTRA TO YOUR ACCOUNT', max_length=255, verbose_name='Freight Terms'),
        ),
    ]
