# Generated by Django 6.1.1 on 2026-09-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_quotation_freight_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='pf_terms',
            field=models.CharField(default='NIL', max_length=255, verbose_name='P&F Terms'),
        ),
    ]
