# Generated by Django 6.1.1 on 2026-09-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_quotation_pf_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(choices=[('PCS', 'PCS'), ('SET', 'SET'), ('NOS', 'NOS'), ('MTR', 'MTR'), ('KG', 'KG'), ('LOT', 'LOT')], default='NOS', max_length=30, verbose_name='Unit'),
        ),
    ]
