# Generated by Django 6.1.1 on 2026-09-25 08:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_alter_quotationitem_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='V210 PUMPS', max_length=100, verbose_name='Category / Series')),
                ('model_code', models.CharField(max_length=200, unique=True, verbose_name='Product / Model Code')),
                ('description', models.TextField(blank=True, verbose_name='Detailed Description')),
                ('unit_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Unit Rate (Rs.)')),
                ('hsn_code', models.CharField(blank=True, default='84136090', max_length=50, verbose_name='HSN Code')),
                ('unit', models.CharField(default='NOS', max_length=30, verbose_name='Default Unit')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='GST %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Product / Price List Item',
                'verbose_name_plural': 'Products / Price List',
                'ordering': ['category', 'model_code'],
            },
        ),
    ]
