# Generated by Django 5.2.17 on 2026-09-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Party / Customer Name')),
                ('email', models.CharField(blank=True, default='', max_length=150, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, default='', max_length=100, verbose_name='Mobile / Phone')),
                ('gstin', models.CharField(blank=True, default='', max_length=50, verbose_name='GSTIN')),
                ('address', models.TextField(blank=True, default='', verbose_name='Full Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer / Client',
                'verbose_name_plural': 'Customers / Clients',
                'ordering': ['name'],
            },
        ),
    ]
