# Generated by Django 5.2.17 on 2026-09-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0011_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(choices=[('PCS', 'PCS'), ('SET', 'SET'), ('NOS', 'NOS'), ('MTR', 'MTR'), ('KG', 'KG'), ('LOT', 'LOT'), ('PAIR', 'PAIR')], default='NOS', max_length=30, verbose_name='Unit'),
        ),
    ]
