# Generated by Django 5.2.17 on 2026-09-26 09:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0012_alter_quotationitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='freight_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Freight (Rs.)'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='pf_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='P&F Amount (Rs.)'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='pf_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='P&F %'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Taxable Amount (Rs.)'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Discount %'),
        ),
    ]
