# Generated by Django 5.2.17 on 2026-09-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0013_quotation_freight_amount_quotation_pf_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='GENERAL', max_length=100, verbose_name='Category / Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_code',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Stock Item Name / Model Code'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['model_code'], name='quotations__model_c_84ad93_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='quotations__categor_d27089_idx'),
        ),
    ]
