# Generated by Django 5.2.17 on 2026-09-28 06:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0014_alter_product_category_alter_product_model_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, verbose_name='Discount %'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='freight_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Freight (Rs.)'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='pf_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='P&F Amount (Rs.)'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='pf_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, verbose_name='P&F %'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Taxable Amount (Rs.)'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Amount (Rs.)'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Unit Rate (Rs.)'),
        ),
    ]
