# Generated by Django 5.2.17 on 2026-09-30 05:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0015_alter_quotation_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default='GENERAL', max_length=100, verbose_name='Category / Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Detailed Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('18.00'), max_digits=5, null=True, verbose_name='GST %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='NOS', max_length=30, verbose_name='Default Unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Unit Rate (Rs.)'),
        ),
    ]
