# Generated by Django 5.2.17 on 2026-09-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0016_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clean_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='Normalized Code (Alphanumeric)'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['clean_code'], name='quotations__clean_c_7f06fc_idx'),
        ),
    ]
