# Generated by Django 5.2.17 on 2026-10-03 06:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0018_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='Quotation Reference No.')),
                ('proforma_number', models.CharField(max_length=100, unique=True, verbose_name='Proforma Invoice No.')),
                ('proforma_date', models.DateField(default=django.utils.timezone.now, verbose_name='Proforma Date')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20, verbose_name='Status')),
                ('company_name', models.CharField(default='MAXFLOW CONTROLS (INDIA) PVT. LTD.', max_length=255)),
                ('company_address', models.TextField(default='18, UNIQUE INDUSTRIAL ESTATE, OFF. VEER SAVARKAR MARG, PRABHADEVI, MUMBAI – 400 025')),
                ('company_contact', models.TextField(default='TEL: 022 – 24360131 / 32, EMAIL: mumbai@maxflowcontrols.com / Cell:8928386417 / GST NO. 27AABCM8025D1ZQ')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer / Company Name')),
                ('customer_address', models.TextField(verbose_name='Customer Address')),
                ('customer_contact', models.CharField(blank=True, default='', max_length=100, verbose_name='Contact No.')),
                ('customer_gstin', models.CharField(blank=True, default='', max_length=50, verbose_name='Customer GSTIN')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Customer Email')),
                ('attention_to', models.CharField(blank=True, default='', max_length=150, verbose_name='Kind Attn.')),
                ('salutation', models.CharField(default='Dear Sir,', max_length=50)),
                ('po_reference', models.CharField(default='Whatsapp', max_length=100, verbose_name='PO / Reference No.')),
                ('po_date', models.DateField(default=django.utils.timezone.now, verbose_name='PO Date')),
                ('subject_note', models.TextField(default='Ref to your Purchase Order#: {po_reference}, dated:.{po_date}, please refer to the prof invoice for releasing Advance payment.', verbose_name='Reference / Subject Opening Note')),
                ('freight_label', models.CharField(default='DTDC BY AIR', max_length=100, verbose_name='Freight / Courier Charge Label')),
                ('freight_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Freight / Courier (Rs.)')),
                ('tax_type', models.CharField(choices=[('IGST', 'IGST (Inter-State 18%)'), ('CGST_SGST', 'CGST + SGST (Intra-State / Maharashtra 9% + 9%)'), ('EXEMPT', 'Exempt / No Tax (0%)')], default='IGST', max_length=20, verbose_name='Tax Type')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='Tax Rate %')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Item Subtotal (Rs.)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Discount (Rs.)')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Taxable Amount (Rs.)')),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='CGST (Rs.)')),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='SGST (Rs.)')),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IGST (Rs.)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Tax (Rs.)')),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Grand Total (Rs.)')),
                ('amount_in_words', models.CharField(blank=True, default='', max_length=500, verbose_name='Amount in Words')),
                ('bank_name', models.CharField(default='ICICI BANK LIMITED.', max_length=150)),
                ('bank_branch', models.CharField(default='PRABHADEVI BRANCH.', max_length=150)),
                ('bank_address', models.TextField(default='KALA ACADEMY, RAVINDRA NATYA MANDIR, PRABHADEVI,\nMUMBAI – 400 028.')),
                ('bank_telephone', models.CharField(default='022 6819 1509.', max_length=100)),
                ('bank_account_name', models.CharField(default='MAXFLOW CONTROLS INDIA PRIVATE LIMITED.', max_length=200)),
                ('bank_account_no', models.CharField(default='005705027366', max_length=100)),
                ('bank_ifsc', models.CharField(default='ICIC0000057', max_length=50)),
                ('bank_micr', models.CharField(default='400229013', max_length=50)),
                ('request_note', models.TextField(default='WE KINDLY REQUEST YOU TO ACKNOWLEDGE THE RECEIPT OF THE ABOVE PROFORMA INVOICE.')),
                ('signatory_company', models.CharField(default='MAXFLOW CONTROLS (I) PVT. LTD.', max_length=200)),
                ('signatory_name', models.CharField(default='Jitendra Desai', max_length=100)),
                ('signatory_designation', models.CharField(default='Manager-Sales (Mumbai)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proformas', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas', to='quotations.quotation', verbose_name='Source Quotation')),
            ],
            options={
                'verbose_name': 'Proforma Invoice',
                'verbose_name_plural': 'Proforma Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(default='01.', max_length=20, verbose_name='Sr. #')),
                ('description', models.TextField(verbose_name='Item Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Qty.')),
                ('unit', models.CharField(default='No', max_length=30, verbose_name='Unit')),
                ('unit_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Unit Rate (Rs.)')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Amount (Rs.)')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.proforma')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
