# Generated by Django 5.2.17 on 2026-10-03 09:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0019_proforma_proformaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Advance Received (Rs.)'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='advance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Advance Received Date'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='advance_label',
            field=models.CharField(blank=True, default='ADVANCE RECEIVED ON OUR A/C', max_length=200, verbose_name='Advance Received Description'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='balance_payable',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Balance Amount Payable by You (Rs.)'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, verbose_name='Discount %'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='round_off_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Round Off (+/-)'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='round_off_enabled',
            field=models.BooleanField(default=True, verbose_name='Enable Rounding Off Total'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='rounded_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Rounding Off Total (Rs.)'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='subtotal_after_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Sub-Total after Discount (Rs.)'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total (Rs.)'),
        ),
    ]
