# Generated by Django 5.2.17 on 2026-10-03 11:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0020_proforma_advance_amount_proforma_advance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Advance Received (Rs.)'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='balance_payable',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Balance Amount Payable by You (Rs.)'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='cgst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='CGST (Rs.)'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Discount (Rs.)'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='freight_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Freight / Courier (Rs.)'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Total (Rs.)'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='igst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='IGST (Rs.)'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='round_off_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, null=True, verbose_name='Round Off (+/-)'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='rounded_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Rounding Off Total (Rs.)'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='sgst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='SGST (Rs.)'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Item Subtotal (Rs.)'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='subtotal_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Sub-Total after Discount (Rs.)'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Total Tax (Rs.)'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('18.00'), max_digits=5, null=True, verbose_name='Tax Rate %'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='tax_type',
            field=models.CharField(blank=True, choices=[('GST', 'GST (18%)'), ('IGST', 'IGST (Inter-State 18%)'), ('CGST_SGST', 'CGST + SGST (Intra-State / Maharashtra 9% + 9%)'), ('EXEMPT', 'Exempt / No Tax (0%)')], default='GST', max_length=20, verbose_name='Tax Type'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Taxable Amount (Rs.)'),
        ),
    ]
