# Generated by Django 5.2.17 on 2026-10-03 11:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0021_alter_proforma_advance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformaitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Amount (Rs.)'),
        ),
        migrations.AlterField(
            model_name='proformaitem',
            name='unit_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Unit Rate (Rs.)'),
        ),
    ]
