# Generated by Django 5.2.17 on 2026-10-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0022_alter_proformaitem_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='advance_label',
            field=models.CharField(blank=True, default='ADVANCE RECEIVED IN OUR A/C', max_length=200, verbose_name='Advance Received Description'),
        ),
    ]
