# Generated by Django 5.2.17 on 2026-10-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0023_alter_proforma_advance_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='po_reference',
            field=models.CharField(default='VERBAL P.O. THROUGH EMAIL', max_length=150, verbose_name='PO / Reference No.'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='salutation',
            field=models.CharField(default='DEAR SIR,', max_length=50),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='subject_note',
            field=models.TextField(default='WE ACKNOWLEDGE WITH THANKS RECEIPT OF YOUR {po_reference} DT. {po_date}, PLEASE FIND BELOW OUR PROFORMA INVOICE FOR YOUR KIND REFERENCE.', verbose_name='Reference / Subject Opening Note'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description of Item'),
        ),
    ]
