# Generated by Django 5.2.17 on 2026-10-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0024_alter_proforma_po_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformaitem',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Item Description'),
        ),
    ]
